name: Generate prebuilds

on:
  workflow_dispatch:
    inputs:
      module_version:
        description: "Module version"
        required: true
        default: "latest"
        type: string
      publish_release:
        description: "Publish release"
        required: false
        default: true
        type: boolean

jobs:
  build:
    strategy:
      matrix:
        platform: [android]
        arch: [arm64, x64, arm]
    uses: digidem/nodejs-mobile-bare-prebuilds/.github/workflows/prebuild.yml@main
    with:
      module_name: "fs-native-extensions"
      module_version: ${{ inputs.module_version }}
      platform: ${{ matrix.platform }}
      arch: ${{ matrix.arch }}

  release:
    if: ${{ inputs.publish_release }}
    needs: build
    uses: digidem/nodejs-mobile-bare-prebuilds/.github/workflows/release.yml@main
    with:
      module_version: ${{ needs.build.outputs.module_version }}
